(use-modules (gnu home)
             (gnu home services)
             (gnu home services desktop)
             (gnu home services sound)
             (gnu packages))

(home-environment
  (packages (specifications->packages
             (list "bat"
                   "cmake"
                   "emacs-aggressive-indent"
                   "emacs-avy"
                   "emacs-circadian"
                   "emacs-company"
                   "emacs-dashboard"
                   "emacs-diminish"
                   "emacs-doom-themes"
                   "emacs-ef-themes"
                   "emacs-eglot"
                   "emacs-elfeed"
                   "emacs-emms"
                   "emacs-exec-path-from-shell"
                   "emacs-f"
                   "emacs-flycheck"
                   "emacs-format-all-the-code"
                   "emacs-gcmh"
                   "emacs-git-gutter-fringe"
                   "emacs-guix"
                   "emacs-json-mode"
                   "emacs-lua-mode"
                   "emacs-magit"
                   "emacs-marginalia"
                   "emacs-markdown-mode"
                   "emacs-modus-themes"
                   "emacs-orderless"
                   "emacs-org-bullets"
                   "emacs-paredit"
                   "emacs-pgtk"
                   "emacs-php-mode"
                   "emacs-projectile"
                   "emacs-rainbow-delimiters"
                   "emacs-rust-mode"
                   "emacs-s"
                   "emacs-standard-themes"
                   "emacs-sudo-edit"
                   "emacs-typescript-mode"
                   "emacs-vertico"
                   "emacs-visual-fill-column"
                   "emacs-vterm"
                   "emacs-web-mode"
                   "emacs-yaml-mode"
                   "font-anonymous-pro"
                   "font-google-noto"
                   "font-google-noto-emoji"
                   "font-google-noto-sans-cjk"
                   "font-hack"
                   "font-jetbrains-mono"
                   "font-liberation"
                   "font-microsoft-cascadia"
                   "gcc-toolchain"
                   "ispell"
                   "libreoffice"
                   "librewolf"
                   "libvterm"
                   "lolcat"
                   "make"
                   "quodlibet"
                   "shfmt"
                   "signal-desktop"
                   "starship"
                   "yt-dlp")))
  (services (list (service home-dbus-service-type)
                  (service home-pipewire-service-type
                           (home-pipewire-configuration
                             (enable-pulseaudio? #t))))))
